version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_DB: bussim
      POSTGRES_USER: bususer
      POSTGRES_PASSWORD: buspass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
